apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr8customerapi
  labels:
    app: fr8-customerapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: fr8customerapi
  template:
    metadata:
      labels:
        app: fr8-customerapi
        service: fr8customerapi
    spec:
      containers:
        - name: fr8customerapi
          image: fr8imgrepo.azurecr.io/fr8customerapi:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: customerapi-config
---
apiVersion: v1
kind: Service
metadata:
  name: fr8customerapi
  labels:
    app: fr8-customerapi
    service: fr8customerapi
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    service: fr8customerapi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customerapi-config
  labels:
    app: fr8customerapi
data:
  ASPNETCORE_URLS: http://+:80
  TaxApiBaseAddress: http://fr8taxapi/
  DBServer: pgserv.postgres.database.azure.com
  DBUser: fr8admin@pgserv
  DBPassword: P@ssword1
  Database: postgresdb 