apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr8web
  labels:
    app: fr8-web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: fr8web
  template:
    metadata:
      labels:
        app: fr8-web
        service: fr8web
    spec:
      containers:
        - name: fr8web
          image: yuvak7/fr8web:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: fr8web-config
---
apiVersion: v1
kind: Service
metadata:
  name: fr8web
  labels:
    app: fr8-web
    service: fr8web
spec:
  type: LoadBalancer
  ports:
    - port: 7070
      targetPort: 80
      protocol: TCP
  selector:
    service: fr8web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fr8web-config
  labels:
    app: fr8web
data:
  ASPNETCORE_URLS: http://+:80
  CustomerApiBaseAddress: http://fr8customerapi/