apiVersion: apps/v1

kind: Deployment

metadata:
  name: pgadmin

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "user@domain.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
            - name: PGADMIN_PORT
              value: "80"
          ports:
            - containerPort: 80
              name: pgadminport
---
apiVersion : v1

kind: Service

metadata:
  name: pgadmin
  labels:
    app: pgadmin

spec:
    type: LoadBalancer
    ports:
      - port: 80
    selector:
      app: pgadmin